const DEFAULT_SOURCES = [
  // Company Blogs
  {
    id: 'openai',
    name: 'OpenAI Blog',
    feedURL: 'https://openai.com/blog/rss.xml',
    websiteURL: 'https://openai.com/blog',
    icon: '🧠',
    category: 'company',
    color: '#10a37f',
    enabled: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    feedURL: 'https://www.anthropic.com/rss.xml',
    websiteURL: 'https://www.anthropic.com/news',
    icon: '🤖',
    category: 'company',
    color: '#c06a2d',
    enabled: true,
  },
  {
    id: 'deepmind',
    name: 'Google DeepMind',
    feedURL: 'https://deepmind.google/blog/rss.xml',
    websiteURL: 'https://deepmind.google/discover/blog',
    icon: '🔵',
    category: 'company',
    color: '#4285f4',
    enabled: true,
  },
  {
    id: 'meta-ai',
    name: 'Meta AI',
    feedURL: 'https://ai.meta.com/blog/feed',
    websiteURL: 'https://ai.meta.com/blog',
    icon: 'Ⓜ',
    category: 'company',
    color: '#0866ff',
    enabled: true,
  },
  {
    id: 'microsoft-ai',
    name: 'Microsoft AI',
    feedURL: 'https://blogs.microsoft.com/ai/feed/',
    websiteURL: 'https://blogs.microsoft.com/ai',
    icon: '🪟',
    category: 'company',
    color: '#00a4ef',
    enabled: true,
  },
  // News Sites
  {
    id: 'techcrunch',
    name: 'TechCrunch AI',
    feedURL: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    websiteURL: 'https://techcrunch.com/category/artificial-intelligence',
    icon: '⚡',
    category: 'news',
    color: '#0a8a00',
    enabled: true,
  },
  {
    id: 'verge',
    name: 'The Verge AI',
    feedURL: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    websiteURL: 'https://www.theverge.com/ai-artificial-intelligence',
    icon: '🔺',
    category: 'news',
    color: '#fa4b00',
    enabled: true,
  },
  {
    id: 'venturebeat',
    name: 'VentureBeat AI',
    feedURL: 'https://venturebeat.com/category/ai/feed/',
    websiteURL: 'https://venturebeat.com/category/ai',
    icon: '📈',
    category: 'news',
    color: '#da1f26',
    enabled: true,
  },
  {
    id: 'wired',
    name: 'Wired AI',
    feedURL: 'https://www.wired.com/feed/tag/ai/latest/rss',
    websiteURL: 'https://www.wired.com/tag/artificial-intelligence',
    icon: '📡',
    category: 'news',
    color: '#000000',
    enabled: true,
  },
  {
    id: 'mit-tech',
    name: 'MIT Technology Review',
    feedURL: 'https://www.technologyreview.com/feed/',
    websiteURL: 'https://www.technologyreview.com',
    icon: '🎓',
    category: 'news',
    color: '#a31f34',
    enabled: true,
  },
  {
    id: 'ai-news',
    name: 'AI News',
    feedURL: 'https://www.artificialintelligence-news.com/feed/',
    websiteURL: 'https://www.artificialintelligence-news.com',
    icon: '📰',
    category: 'news',
    color: '#6200ea',
    enabled: true,
  },
  // Research
  {
    id: 'arxiv-ai',
    name: 'ArXiv AI',
    feedURL: 'https://export.arxiv.org/rss/cs.AI',
    websiteURL: 'https://arxiv.org/list/cs.AI/recent',
    icon: '📄',
    category: 'research',
    color: '#b31b1b',
    enabled: true,
  },
  {
    id: 'arxiv-ml',
    name: 'ArXiv ML',
    feedURL: 'https://export.arxiv.org/rss/cs.LG',
    websiteURL: 'https://arxiv.org/list/cs.LG/recent',
    icon: '🔢',
    category: 'research',
    color: '#b31b1b',
    enabled: true,
  },
];

const CATEGORY_LABELS = {
  company: 'Company',
  news: 'News',
  research: 'Research',
  social: 'Social',
};

const REPORT_CATEGORIES = [
  {
    id: 'models',
    label: 'Models & Research',
    emoji: '🧠',
    keywords: ['model', 'llm', 'neural', 'gpt', 'claude', 'gemini', 'research', 'paper', 'arxiv', 'benchmark', 'training', 'fine-tun', 'language model', 'multimodal'],
  },
  {
    id: 'industry',
    label: 'Industry & Business',
    emoji: '💼',
    keywords: ['funding', 'acquisition', 'invest', 'startup', 'revenue', 'partnership', 'deal', 'valuation', 'ipo', 'billion', 'million', 'raises'],
  },
  {
    id: 'policy',
    label: 'Policy & Safety',
    emoji: '⚖️',
    keywords: ['regulation', 'policy', 'safety', 'ethics', 'eu ai act', 'ban', 'law', 'government', 'congress', 'senate', 'risk', 'alignment', 'bias'],
  },
  {
    id: 'products',
    label: 'Products & Tools',
    emoji: '🛠️',
    keywords: ['launch', 'release', 'feature', 'update', 'product', 'app', 'tool', 'api', 'plugin', 'integration', 'new', 'introduces', 'announces'],
  },
  {
    id: 'opensource',
    label: 'Open Source',
    emoji: '🔓',
    keywords: ['open source', 'open-source', 'github', 'repository', 'released code', 'weights', 'hugging face', 'open model', 'open weight'],
  },
];
